### ISSUE TITLE
conjugate method crashed in 2.0.8

### ISSUE THREAD

**Issue by casevh** [aleaxit/gmpy#194]
gmpy2.mpg("1+2j").conjugate() causes a core dump.

**Comment by casevh** [comment]
This has been fixed.

**Comment by achan001** [comment]
Is the fix applied to gmpy2?
I downloaded winpython 3.8.9 (Python 3.8), the bug still there.
```
py3> import gmpy2
py3> gmpy2.version()
'2.0.8'
py3> gmpy2.mpc('1+2j').conjugate() # system crash
```

And, same bug for Python 2.6.6
You had gmpy2 2.0.9 specially made for my Python 2.6.6, a long time ago.
```
>>> import gmpy2
>>> gmpy2.version()
'2.0.9'
>>> gmpy2.mpc('1+2j').conjugate() # system crash
