### ISSUE TITLE
gmpy2 2.2.0a2 missing on PyPI

### ISSUE THREAD

**Issue by hartwork** [aleaxit/gmpy#476]
Hello gmpy! :wave: 

Release [gmpy2 2.2.0a2](https://github.com/aleaxit/gmpy/releases/tag/gmpy2-2.2.0a2) is [missing on PyPI](https://pypi.org/project/gmpy2/#history). Is there a chance it could be added?

Thanks and best, Sebastian

CC @hannob

**Comment by casevh** [comment]
I am testing what should become gmpy2 2.2.0b1.

**Comment by skirpichev** [comment]
CI fails on the master; fix: https://github.com/aleaxit/gmpy/pull/477

**Comment by casevh** [comment]
Thanks. You're too quick. Will merge after all the tests complete.

**Comment by casevh** [comment]
I have uploaded gmpy2 2.2.0rc1. Please test and I'll make a official release soon.

**Comment by casevh** [comment]
I have published gmpy2 2.2.0.

**Comment by hartwork** [comment]
Thank you! gmpy2 2.2.0a2 is still missing on PyPI, but with 2.2.0 available now, I believe this can be closed as fixed. (Please re-open if there is need to, just trying to help.)
